wallet: remove wid from index when wallet is removed
handshake-org/hsd pull request #520
Opened 2020-10-20 01:36 UTC by chikeichan

This fixes an issue where wallet ids were still stored in `OutpointMap`, `TXMap`, and `NameMap` after the wallet is removed, causing rescan of any wallet containing a matching `outpoint`, `tx`, or `name` to fail due to this [exception](https://github.com/handshake-org/hsd/blob/master/lib/wallet/walletdb.js#L2310).

This fix does two things:
- only return current `wid` when `getWalletsByTX` is called
- if old `wid` are found, remove from the corresponding map

2020-10-25 19:11 UTC, pinheadmz commented on lib/wallet/walletdb.js
> +            await this.removeOutpointMap(b, hash, index, wid);
I think `getWalletsByTX()` is the wrong place to be deleting records from the database. 
If you look at `_remove()`: https://github.com/handshake-org/hsd/blob/c85d9b4c743a9e1c9577d840e1bd20dee33473d3/lib/wallet/walletdb.js#L995-L1094

I see `removePathMap()`, `removeBlockMap()`, `removeOutpointMap()`, and `removeTXMap()` along with the other per-wallet buckets being wiped. 

So I think you are right that `_remove()` might be missing `removeNameMap()` and I think that should be the first thing to check if you are seeing leftover data causing unexpected behavior after removing a wallet.

The function `getWalletsByTX()` should not do anything except tell you which wallets are interested in a transaction :-) adding extra database calls here I think is the wrong approach and will confuse future developers.

In the same vein, the test should be able check that all data is cleared from the database after just calling `remove()`

2020-10-29 20:12 UTC, chikeichan commented
moved db ops from `getWalletsByTx` to `remove`, also updated test for testing `NameMap`!

2021-01-13 19:55 UTC, pinheadmz requested changes
Thanks @chikeichan sorry it took so long to review. Just a few nits and then if you can squash down to one commit and rebase on master, I think it's done. Thank you!

2021-01-13 20:46 UTC, pinheadmz commented
Integration test process:

1. Backup wallet directory: `cp -r ~/.hsd/wallet ~/.hsd/wallet-backup`
2. Check out master branch (no PR)
3. Since `remove()` is not exposed in API, hard code a removal in `walletDB.open()`: `await this.remove('<wallet name>');`
4. Start hsd: `hsd` -- wallet will be removed on launch (no log messages)
5. Trigger rescan: `hsw-cli rescan`

As soon as the rescan hits the first auction-related transaction (in my case, an OPEN) which would be identified by the corrupted `nameMap`, an assertion error is thrown:

```
[info] (wallet) Incoming transaction for 1 wallets in WalletDB (ea1ed2422caca1b73bcad65692ecb587706a9f74ac192a413c211fdadd5aaafc).
[error] (node) Assertion failed.
    at WalletDB._addTX (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2399:7)
    at async WalletDB._addBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2240:13)
    at async WalletDB.rescanBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2345:7)
    at async /Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:150:9
    at async NodeClient._emitAsync (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bevent/lib/asyncemitter.js:377:11)
    at async NodeClient.emitAsync (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bevent/lib/asyncemitter.js:318:7)
    at async ChainDB.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chaindb.js:1510:7)
    at async Chain.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:1888:14)
    at async WalletDB.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:502:7)
    at async WalletDB.rescan (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:604:14)
[error] (node) Assertion failed.
    at WalletDB._addTX (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2399:7)
    at async WalletDB._addBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2240:13)
    at async WalletDB.rescanBlock (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:2345:7)
    at async /Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:150:9
    at async NodeClient._emitAsync (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bevent/lib/asyncemitter.js:377:11)
    at async NodeClient.emitAsync (/Users/matthewzipkin/Desktop/work/hsd/node_modules/bevent/lib/asyncemitter.js:318:7)
    at async ChainDB.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chaindb.js:1510:7)
    at async Chain.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/blockchain/chain.js:1888:14)
    at async WalletDB.scan (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:502:7)
    at async WalletDB.rescan (/Users/matthewzipkin/Desktop/work/hsd/lib/wallet/walletdb.js:604:14)
```

I notice this is not the same error you located in your original post - but it still makes sense. The error you linked to would be thrown in the case of a reorg (because it's in the middle of `_removeBlock()`) whereas in my example its getting caught on a rescan as transactions are inserted in `_addTX()`. Either way - the error is reproduceable.

Now to test the PR:

1. Checkout this PR branch
2. Replace original walletDB: `rm -rf ~/.hsd/wallet; cp -r ~/.hsd/wallet-backup/ ~/.hsd/wallet`
3. Re-apply the `remove()` call in `walletDB.open()`
4. Start hsd: `hsd`
5. Confirm wallet is deleted: `hsw-cli wallets`
6. Trigger rescan: `hsw-cli rescan 0`

Success! no assertion errors.

GOOD JOB DUDE. 🚀

2021-02-03 21:17 UTC, pinheadmz commented
@chikeichan I'm interested in getting this merged since its an easy bug fix. I opened a PR to your branch here https://github.com/kyokan/hsd/pull/7 with a little clean up commit. See if you wanna merge that in to your branch? Ideally squash the commits you already have and we can merge to hsd master. Or if you want I'm happy just to close this PR and merge my own branch, you'll still get the commit credit :-)

2021-02-04 16:44 UTC, pinheadmz commented
Closed by https://github.com/handshake-org/hsd/commit/4c7db7fed18d1eadf14aa0b2b67ce42814581d7f

2021-02-04 16:44 UTC, closed without merging