Fix npm warning
handshake-org/hsd pull request #776
Opened 2022-11-02 15:07 UTC by NetOpWibby

Apparently, `--omit=dev` should be used over `--production`.

2022-11-04 23:20 UTC, rtdev-com requested changes
Need to fix a typo

2022-11-04 23:20 UTC, rtdev-com commented on docs/install.md
> +npm install --omit-dev
```suggestion
npm install --omit=dev
```

2022-11-04 23:41 UTC, NetOpWibby commented on docs/install.md
> +npm install --omit-dev
Oh man, nice catch!

2022-11-05 00:04 UTC, rtdev-com approved these changes

2022-11-05 13:12 UTC, pinheadmz commented
grep the repo for `production`, there are two more places to change I think: `Dockerfile` and `CONTRIBUTING.md` can you find anything else like this that needs to be updated?

2022-11-06 00:35 UTC, NetOpWibby commented
`grep -irn "\-\-production"` shows:

```
./Dockerfile:9:RUN npm install --production
./docs/install.md:36:npm install --production
./CONTRIBUTING.md:23:"developer dependency" if installed without the `--production` flag. The
```

2022-11-06 00:46 UTC, NetOpWibby commented
@pinheadmz All set!

2022-11-11 16:43 UTC, pinheadmz commented
CI was failing on node v12 which is unsupported now anyway. Removing that so this docs-only PR will pass integration tests!

2022-11-11 17:48 UTC, pinheadmz commented
Ugh, @chjj's DNS seed server is down. I'm gonna fix this flakey test by targeting `nic.com` a much more reliable name for lookups.

2022-11-11 17:59 UTC, pinheadmz commented
Ugh part III: Fine lets just skip the test that requires external DNS lookups, for now.

2022-11-11 18:14 UTC, merged