Update http.js
handshake-org/hsd pull request #830
Opened 2023-07-18 22:26 UTC by eskimo

This adds http handlers for the createclaim/sendclaim rpc methods.

This was made for shakestation so I could select which wallet to create/send claims from without having to rpc selectwallet which could potentially break other scripts that may have been running at the same time.

2023-12-18 17:35 UTC, nodech commented
I think it would be more appropriate if it followed convention for the name related endpoints.

`POST /wallet/:id/open` - used for creating and sending open
`POST /wallet/:id/bid` - used for creating and sending bid
etc..

Accepting post data: `name` for providing name and `broadcast`  - if we want to send right away.
Also test and hs-client wallet update would make this PR complete.

2024-05-10 07:57 UTC, Falci requested changes
Make lint happy

2024-05-10 07:57 UTC, Falci commented on lib/wallet/http.js
> +
```suggestion
      const name = valid.str('name');

```

2024-05-10 07:57 UTC, Falci commented on lib/wallet/http.js
> +
```suggestion
      const name = valid.str('name');

```

2024-12-27 10:17 UTC, closed without merging